---
- name: Remove legacy Docker packages
  ansible.builtin.apt:

    name:

      - docker

      - docker-engine

      - docker.io

      - podman-docker

      - containerd

      - runc

    state: absent

  when: docker_remove_old_packages

- name: Install prerequisites
  ansible.builtin.apt:

    name:

      - ca-certificates

      - curl

      - gnupg

      - lsb-release

    state: present

    update_cache: true
