all:
  children:
    docker:
      children:

        # Environments
        production:
          hosts:
            shack-app-p001:
              ansible_host: 10.0.0.91
              docker_swarm_bootstrap: true
            shack-app-p002:
              ansible_host: 10.0.0.92
            #  shack-app-p003:
            #    ansible_host: 10.0.0.93
            shack-app-p004:
              ansible_host: 10.0.0.94

        testing:
          hosts:
            shack-app-t001:
              ansible_host: 10.0.0.61
              docker_swarm_bootstrap: true
            shack-app-t002:
              ansible_host: 10.0.0.62
            #  shack-app-t003:
            #    ansible_host: 10.0.0.63
            shack-app-t004:
              ansible_host: 10.0.0.64

        development:
          hosts:
            shack-app-d001:
              ansible_host: 10.0.0.31
              docker_swarm_bootstrap: true
            shack-app-d002:
              ansible_host: 10.0.0.32
            #  shack-app-d003:
            #    ansible_host: 10.0.0.33
            shack-app-d004:
              ansible_host: 10.0.0.34

        management:
          hosts:
            shack-mgmt-004:
              ansible_host: 10.0.0.23
              docker_swarm_bootstrap: true


        # Roles
        managers:
          hosts:
            shack-app-p001:
            #  shack-app-p002:
            #  shack-app-p003:
            #  shack-app-p004:

            shack-app-t001:
            shack-app-t002:
            shack-app-t003:
            shack-app-t004:

            shack-app-d001:
            shack-app-d002:
            shack-app-d003:
            shack-app-d004:

            shack-mgmt-001:


        # workers:
