---
- name: Ensure Docker is running
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Check current swarm state
  ansible.builtin.command:
    cmd: docker info --format '{{ "{{.Swarm.LocalNodeState}}" }}'
  register: docker_swarm_state
  changed_when: false

- name: Join Docker Swarm
  community.docker.docker_swarm:
    state: join
    join_token: "{{ docker_swarm_join_token_result.stdout }}"
    advertise_addr: "{{ ansible_host }}"
    remote_addrs: "{{ hostvars[docker_swarm_manager].ansible_host }}"
  when:
    - docker_swarm_state.stdout != "active"
