---
- name: Initialize Docker swarm
  ansible.builtin.command:
    cmd: >
      docker swarm init
      --advertise-addr {{ docker_swarm_advertise_addr }}
  when:
    - docker_swarm_state.stdout == "inactive"
  register: swarm_init
